sudo: required
services:
  - docker

before_install:
  - docker build -t andreipop85/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andreipop85/react-test npm test -- --coverage

after_success:
  - docker build -t andreipop85/multi-client ./client
  - docker build -t andreipop85/multi-nginx ./nginx
  - docker build -t andreipop85/multi-server ./server
  - docker build -t andreipop85/multi-worker ./worker
  # loging into docker
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push andreipop85/multi-client
  - docker push andreipop85/multi-nginx
  - docker push andreipop85/multi-server
  - docker push andreipop85/multi-worker